# 4.8: Grouping Data & Aggregating Variables

### Task 1

In [1]:
# import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# assign the path of file to be imported into the variable 'path'

path=r'C:\Users\19452\Desktop\Seema\Careerfoundry-Data Analytics Course\Work Area\Python Fundamentals\Nov-2023 Instacart Basket Analysis\02 Data\Prepared Data'


# import 'ords_prods_merge.pkl' from prepared data folder and assign it to the 'ords_prods_merge' dataframe

ords_prods_merge=pd.read_pickle(os.path.join(path,'ords_prods_merge.pkl'))

In [3]:
# Look for the newly added columns 'Busiest days' and 'busiest_period_of_day' in the imported dataset

ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,merge_flag,price_range_loc,Busiest days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,2539329.0,1.0,1.0,2.0,8.0,NaN,196.0,1.0,0.0,Soda,...,both,Mid-range product,Regular day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
1,2398795.0,1.0,2.0,3.0,7.0,15.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
2,473747.0,1.0,3.0,3.0,12.0,21.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
3,2254736.0,1.0,4.0,4.0,7.0,29.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
4,431534.0,1.0,5.0,4.0,15.0,28.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer

### Task 2 - find the aggregated mean of the 'order_number' column grouped by 'department_id' for the entire 'ords_prods_merge' dataframe

In [4]:
# Split the data into groups based on “department_id.”
# Apply the aggregate function to each group to obtain the mean values for the “order_number” column.

ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1.0     15.457838
2.0     17.277920
3.0     17.170395
4.0     17.811403
5.0     15.215751
6.0     16.439806
7.0     17.225802
8.0     15.340650
9.0     15.895474
10.0    20.197148
11.0    16.170638
12.0    15.887671
13.0    16.583536
14.0    16.773669
15.0    16.165037
16.0    17.665606
17.0    15.694469
18.0    19.310397
19.0    17.177343
20.0    16.473447
21.0    22.902379
Name: order_number, dtype: float64

### Task 3 - How do the results for the entire dataframe differ from those of the subset?

#### There are 21 department_id groups in the entire dataframe when compared to 7 in the subset.
#### The mean values of order_number vary in both the groups as the count of records are different in both the datasets.

### Task 4 -Create a loyalty flag for existing customers using the transform() and loc() functions.

In [5]:
# Split the data into groups based on the “user_id” column.
# Apply the transform() function on the “order_number” column to generate the maximum orders for each user.
# Create a new column, “max_order,” into which you’ll place the results of your aggregation.

ords_prods_merge['max_order']=ords_prods_merge.groupby('user_id')['order_number'].transform(np.max)

C:\Users\19452\AppData\Local\Temp\ipykernel_2840\338669930.py:5: FutureWarning: The provided callable <function amax at 0x00000160B4BA1D00> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order']=ords_prods_merge.groupby('user_id')['order_number'].transform(np.max)

In [6]:
# check the newly created column 'max_order'

ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,merge_flag,price_range_loc,Busiest days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,2539329.0,1.0,1.0,2.0,8.0,NaN,196.0,1.0,0.0,Soda,...,both,Mid-range product,Regular day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
1,2398795.0,1.0,2.0,3.0,7.0,15.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
2,473747.0,1.0,3.0,3.0,12.0,21.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
3,2254736.0,1.0,4.0,4.0,7.0,29.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
4,431534.0,1.0,5.0,4.0,15.0,28.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer

#### Loyal customers are those with max_order more than around 70th percentile and New customers are the ones with max_order less than 20th percentile.  All in between values are considered Regular customers.

In [7]:
# create a loyalty flag that assigns a loyalty label to a user ID based on its corresponding max order value.

ords_prods_merge.loc[ords_prods_merge['max_order']>40,'loyalty_flag']='Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order']<=40) & (ords_prods_merge['max_order']>10),'loyalty_flag']='Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order']<=10,'loyalty_flag']='New customer'

In [8]:
# Look the value count of each loyalty_flag

ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    16381472
Loyal customer      10679578
New customer         5580218
NaN                       11
Name: count, dtype: int64

In [9]:
# check the newly added column 'loyalty_flag'

ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,merge_flag,price_range_loc,Busiest days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,2539329.0,1.0,1.0,2.0,8.0,NaN,196.0,1.0,0.0,Soda,...,both,Mid-range product,Regular day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
1,2398795.0,1.0,2.0,3.0,7.0,15.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
2,473747.0,1.0,3.0,3.0,12.0,21.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
3,2254736.0,1.0,4.0,4.0,7.0,29.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
4,431534.0,1.0,5.0,4.0,15.0,28.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer

### Task 5 - determine whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [10]:
# Group the customers by 'loyalty_flag' and calculate mean, min and max on prices spent on products to understand the
# spending habits of the three types of customers identified.

ords_prods_merge.groupby('loyalty_flag').agg({'prices':['mean','min','max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.377144  1.0  99999.0
New customer      13.208437  1.0  99999.0
Regular customer  12.616225  1.0  99999.0

#### The above results shows that the New customers spent the most, followed by Regular customers and then the Loyal customers.

### Task 6 - find the average prices of items people are buying to determine different types of spenders

In [11]:
# Split the data into groups based on the “user_id” column.
# Apply the transform() function on the “prices” column to generate the average price accross all orders for each user.
# assign the average price values to a variable 'average spent'

ords_prods_merge['average spent']=ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

C:\Users\19452\AppData\Local\Temp\ipykernel_2840\1425996820.py:5: FutureWarning: The provided callable <function mean at 0x00000160B4BA2A20> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['average spent']=ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

#### 25th percentile of average_spent is 7.  Rounded this to below 10 to mark the low spender.  spending flag assigns a spending label to each user based on aggregation

In [12]:
# Create a new column, “spending flag,” into which the label based on aggregation is assigned.

ords_prods_merge.loc[ords_prods_merge['average spent']>=10,'spending flag']='High spender'
ords_prods_merge.loc[ords_prods_merge['average spent']<10,'spending flag']='Low spender'

In [13]:
# This command tells pandas not to assign any options regarding the maximum number of rows to display. For ex, when using
# head() function to display more records say, head(100).  All 100 rows would display if the below code is run

pd.options.display.max_rows=None

In [14]:
# Look at the mean values in 'spending flag' column for each user

ords_prods_merge[['user_id','prices','average spent','spending flag']].head(100)

    user_id  prices  average spent spending flag
0       1.0     9.0       6.367797   Low spender
1       1.0     9.0       6.367797   Low spender
2       1.0     9.0       6.367797   Low spender
3       1.0     9.0       6.367797   Low spender
4       1.0     9.0       6.367797   Low spender
5       1.0     9.0       6.367797   Low spender
6       1.0     9.0       6.367797   Low spender
7       1.0     9.0       6.367797   Low spender
8       1.0     9.0       6.367797   Low spender
9       1.0     9.0       6.367797   Low spender
10     15.0     9.0       3.980556   Low spender
11     15.0     9.0       3.980556   Low spender
12     15.0     9.0       3.980556   Low spender
13     15.0     9.0       3.980556   Low spender
14     15.0     9.0       3.980556   Low spender
15     19.0     9.0       8.372059   Low spender
16     19.0     9.0       8.372059   Low spender
17     19.0     9.0       8.372059   Low spender
18     21.0     9.0       7.012683   Low spender
19     31.0     9.0       8.137793   Low spender
20     31.0     9.0       8.137793   Low spender
21     43.0     9.0       7.444898   Low spender
22     43.0     9.0       7.444898   Low spender
23     52.0     9.0       6.356287   Low spender
24     52.0     9.0       6.356287   Low spender
25     52.0     9.0       6.356287   Low spender
26     52.0     9.0       6.356287   Low spender
27     52.0     9.0       6.356287   Low spender
28     52.0     9.0       6.356287   Low spender
29     52.0     9.0       6.356287   Low spender
30     52.0     9.0       6.356287   Low spender
31     52.0     9.0       6.356287   Low spender
32     52.0     9.0       6.356287   Low spender
33     52.0     9.0       6.356287   Low spender
34     52.0     9.0       6.356287   Low spender
35     52.0     9.0       6.356287   Low spender
36     52.0     9.0       6.356287   Low spender
37     67.0     9.0       7.656790   Low spender
38     67.0     9.0       7.656790   Low spender
39     67.0     9.0       7.656790   Low spender
40     67.0     9.0       7.656790   Low spender
41     67.0     9.0       7.656790   Low spender
42     67.0     9.0       7.656790   Low spender
43     67.0     9.0       7.656790   Low spender
44     67.0     9.0       7.656790   Low spender
45     67.0     9.0       7.656790   Low spender
46     67.0     9.0       7.656790   Low spender
47     67.0     9.0       7.656790   Low spender
48     67.0     9.0       7.656790   Low spender
49     67.0     9.0       7.656790   Low spender
50     67.0     9.0       7.656790   Low spender
51     67.0     9.0       7.656790   Low spender
52     67.0     9.0       7.656790   Low spender
53     67.0     9.0       7.656790   Low spender
54     67.0     9.0       7.656790   Low spender
55     67.0     9.0       7.656790   Low spender
56     81.0     9.0       8.165385   Low spender
57     81.0     9.0       8.165385   Low spender
58     82.0     9.0       6.441221   Low spender
59     82.0     9.0       6.441221   Low spender
60     82.0     9.0       6.441221   Low spender
61     82.0     9.0       6.441221   Low spender
62     82.0     9.0       6.441221   Low spender
63     82.0     9.0       6.441221   Low spender
64     82.0     9.0       6.441221   Low spender
65     82.0     9.0       6.441221   Low spender
66     82.0     9.0       6.441221   Low spender
67     98.0     9.0       8.028000   Low spender
68     98.0     9.0       8.028000   Low spender
69     98.0     9.0       8.028000   Low spender
70     98.0     9.0       8.028000   Low spender
71     98.0     9.0       8.028000   Low spender
72     98.0     9.0       8.028000   Low spender
73     98.0     9.0       8.028000   Low spender
74    109.0     9.0       5.850725   Low spender
75    120.0     9.0       9.385714   Low spender
76    120.0     9.0       9.385714   Low spender
77    185.0     9.0       7.715000   Low spender
78    195.0     9.0       7.149730   Low spender
79    195.0     9.0       7.149730   Low spender
80    195.0     9.0       7.149730   Low spender
81    195.0     9.0       7.149730   Low spender
82    195.0     9.0       7.149730   Low spender
83    195.0     9.0       7.149730   Low spender
84    195.0     9.0       7.149730   Low spender
85    195.0     9.0       7.149730   Low spender
86    195.0     9.0       7.149730   Low spender
87    195.0     9.0       7.149730   Low spender
88    195.0     9.0       7.149730   Low spender
89    195.0     9.0       7.149730   Low spender
90    222.0     9.0       6.862397   Low spender
91    222.0     9.0       6.862397   Low spender
92    290.0     9.0       7.285597   Low spender
93    290.0     9.0       7.285597   Low spender
94    331.0     9.0       7.705128   Low spender
95    360.0     9.0      10.006250  High spender
96    377.0     9.0       8.496552   Low spender
97    387.0     9.0       7.396610   Low spender
98    420.0     9.0       7.387805   Low spender
99    420.0     9.0       7.387805   Low spender

In [15]:
# Look at the value count of the new flag column

ords_prods_merge['spending flag'].value_counts(dropna=False)

spending flag
Low spender     32001233
High spender      640035
NaN                   11
Name: count, dtype: int64

## Task 7 - determine frequent versus non-frequent customers

In [16]:
# Group records by 'user_id', calculate median of 'days_since_prior_order' and assign the aggregation result 
# to variable'regularity'

ords_prods_merge['regularity']=ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

C:\Users\19452\AppData\Local\Temp\ipykernel_2840\1501536339.py:4: FutureWarning: The provided callable <function median at 0x00000160B4CE79C0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['regularity']=ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [17]:
# based on the 'regularity' value the new column 'order frequency flag' gets appropriate label

ords_prods_merge.loc[ords_prods_merge['regularity']>20,'order frequency flag']='Non-frequent customer'
ords_prods_merge.loc[(ords_prods_merge['regularity']>10) & (ords_prods_merge['regularity']<=20),'order frequency flag']='Regular customer'
ords_prods_merge.loc[ords_prods_merge['regularity']<=10,'order frequency flag']='Frequent customer'

In [18]:
# Look at the newly added flag cloumn

ords_prods_merge[['user_id','regularity','order frequency flag']].head(100)

    user_id  regularity   order frequency flag
0       1.0        20.0       Regular customer
1       1.0        20.0       Regular customer
2       1.0        20.0       Regular customer
3       1.0        20.0       Regular customer
4       1.0        20.0       Regular customer
5       1.0        20.0       Regular customer
6       1.0        20.0       Regular customer
7       1.0        20.0       Regular customer
8       1.0        20.0       Regular customer
9       1.0        20.0       Regular customer
10     15.0        10.0      Frequent customer
11     15.0        10.0      Frequent customer
12     15.0        10.0      Frequent customer
13     15.0        10.0      Frequent customer
14     15.0        10.0      Frequent customer
15     19.0         6.0      Frequent customer
16     19.0         6.0      Frequent customer
17     19.0         6.0      Frequent customer
18     21.0         8.0      Frequent customer
19     31.0         6.0      Frequent customer
20     31.0         6.0      Frequent customer
21     43.0        10.0      Frequent customer
22     43.0        10.0      Frequent customer
23     52.0         8.0      Frequent customer
24     52.0         8.0      Frequent customer
25     52.0         8.0      Frequent customer
26     52.0         8.0      Frequent customer
27     52.0         8.0      Frequent customer
28     52.0         8.0      Frequent customer
29     52.0         8.0      Frequent customer
30     52.0         8.0      Frequent customer
31     52.0         8.0      Frequent customer
32     52.0         8.0      Frequent customer
33     52.0         8.0      Frequent customer
34     52.0         8.0      Frequent customer
35     52.0         8.0      Frequent customer
36     52.0         8.0      Frequent customer
37     67.0         7.0      Frequent customer
38     67.0         7.0      Frequent customer
39     67.0         7.0      Frequent customer
40     67.0         7.0      Frequent customer
41     67.0         7.0      Frequent customer
42     67.0         7.0      Frequent customer
43     67.0         7.0      Frequent customer
44     67.0         7.0      Frequent customer
45     67.0         7.0      Frequent customer
46     67.0         7.0      Frequent customer
47     67.0         7.0      Frequent customer
48     67.0         7.0      Frequent customer
49     67.0         7.0      Frequent customer
50     67.0         7.0      Frequent customer
51     67.0         7.0      Frequent customer
52     67.0         7.0      Frequent customer
53     67.0         7.0      Frequent customer
54     67.0         7.0      Frequent customer
55     67.0         7.0      Frequent customer
56     81.0        30.0  Non-frequent customer
57     81.0        30.0  Non-frequent customer
58     82.0        12.0       Regular customer
59     82.0        12.0       Regular customer
60     82.0        12.0       Regular customer
61     82.0        12.0       Regular customer
62     82.0        12.0       Regular customer
63     82.0        12.0       Regular customer
64     82.0        12.0       Regular customer
65     82.0        12.0       Regular customer
66     82.0        12.0       Regular customer
67     98.0        25.0  Non-frequent customer
68     98.0        25.0  Non-frequent customer
69     98.0        25.0  Non-frequent customer
70     98.0        25.0  Non-frequent customer
71     98.0        25.0  Non-frequent customer
72     98.0        25.0  Non-frequent customer
73     98.0        25.0  Non-frequent customer
74    109.0        26.0  Non-frequent customer
75    120.0        19.0       Regular customer
76    120.0        19.0       Regular customer
77    185.0        25.0  Non-frequent customer
78    195.0         4.0      Frequent customer
79    195.0         4.0      Frequent customer
80    195.0         4.0      Frequent customer
81    195.0         4.0      Frequent customer
82    195.0         4.0      Frequent customer
83    195.0         4.0      Frequent customer
84    195.0         4.0      Frequent customer
85    195.0         4.0      Frequent customer
86    195.0         4.0      Frequent customer
87    195.0         4.0      Frequent customer
88    195.0         4.0      Frequent customer
89    195.0         4.0      Frequent customer
90    222.0         5.0      Frequent customer
91    222.0         5.0      Frequent customer
92    290.0         7.0      Frequent customer
93    290.0         7.0      Frequent customer
94    331.0        30.0  Non-frequent customer
95    360.0         4.0      Frequent customer
96    377.0        30.0  Non-frequent customer
97    387.0         8.0      Frequent customer
98    420.0         8.0      Frequent customer
99    420.0         8.0      Frequent customer

In [19]:
# Check all the new column added

ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,merge_flag,price_range_loc,Busiest days,busiest_period_of_day,max_order,loyalty_flag,average spent,spending flag,regularity,order frequency flag
0,2539329.0,1.0,1.0,2.0,8.0,NaN,196.0,1.0,0.0,Soda,...,both,Mid-range product,Regular day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
1,2398795.0,1.0,2.0,3.0,7.0,15.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
2,473747.0,1.0,3.0,3.0,12.0,21.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
3,2254736.0,1.0,4.0,4.0,7.0,29.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Fewest orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer
4,431534.0,1.0,5.0,4.0,15.0,28.0,196.0,1.0,1.0,Soda,...,both,Mid-range product,Least busy day,Most orders,11.0,Regular customer,6.367797,Low spender,20.0,Regular customer

In [20]:
# Look at the value count of the new flag column

ords_prods_merge['order frequency flag'].value_counts(dropna=False)

order frequency flag
Frequent customer        21639188
Regular customer          7287469
Non-frequent customer     3714611
NaN                            11
Name: count, dtype: int64

### Task 9 - Export dataframe as pickle file and store it in 'Prepared Data' folder

In [21]:
# Export 'ords_prods_merge' dataframe to prepared data folder in pickle format

ords_prods_merge.to_pickle(os.path.join(path,'ords_prods_merge.pkl'))